version: "3.5"
services:     
  suggesty_backend:
    restart: always 
    container_name: suggesty_backend
    build: suggesty_backend_django
    env_file:
      - ./suggesty_backend_django/.env
    ports:
      - "8000:8000"
    networks:
      - backend.api

  suggesty_frontend:
    restart: always
    container_name: suggesty_frontend
    build: suggesty_frontend_angular
    ports:
      - "80:80"
      - "4200:80"
    networks:
      - frontend.api

networks:
  backend.api:
    name:
      suggesty_backend
  frontend.api:
    name:
      suggesty_frontend