version: "3.5"
services:     
  suggestybackend:
    container_name: suggestybackend
    build: suggesty_backend_django
    env_file:
      - ./suggesty_backend_django/.env
    ports:
      - "8000:8000"
    networks:
      - backend.api

  suggestyfrontend:
    container_name: suggestyfrontend
    build: suggesty_frontend_angular
    ports:
      - "80:80"

    networks:
      - frontend.api

networks:
  backend.api:
    name:
      suggestybackend
  frontend.api:
    name:
      suggestyfrontend